server {
    listen 80;
    server_name ecg.heremy.link;

    # Se sei in produzione, questa logica ti fa il redirect a HTTPS
    # Se sei in locale, Nginx ignorerà il redirect se non trova i certificati
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API Proxy
    location /api/predict/ {
        proxy_pass http://prediction-service:8000/predict/;
    }
    
    location /api/history/ {
        proxy_pass http://history-service:8001/history/;
    }
}